Revert^2 "Power: Using only v3 powerhal version for this branch""
This reverts commit 1235b53c858209c0d96a87ec77957e9fb6370ab1.

[1] - Fix error build on A14

FAILED: out/target/product/spes/obj/EXECUTABLES/android.hardware.power-service_intermediates/PowerHintSession.o
/bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-r487747c/bin/clang++ -I external/libxml2/include -I external/icu/icu4c/source/common -I vendor/qcom/opensource/power -I out/target/product/spes/obj/EXECUTABLES/android.hardware.power-service_intermediates -I out/target/product/spes/gen/EXECUTABLES/android.hardware.power-service_intermediates  -Isystem/logging/liblog/include_vndk -Isystem/core/libcutils/include_outside_system -Isystem/core/libprocessgroup/include -Isystem/core/libcutils/include -Iexternal/libxml2/include -Isystem/libbase/include -Iexternal/fmtlib/include -Isystem/core/libutils/include -Isystem/libbase/include -Iexternal/fmtlib/include -Isystem/core/libcutils/include_outside_system -Isystem/logging/liblog/include_vndk -Isystem/core/libprocessgroup/include -Isystem/core/libsystem/include -Iframeworks/native/libs/binder/ndk/include_cpp -Iframeworks/native/libs/binder/ndk/include_ndk -Iframeworks/native/libs/binder/ndk/include_platform -Iframeworks/native/libs/binder/ndk/include_cpp -Iframeworks/native/libs/binder/ndk/include_ndk -Iframeworks/native/libs/binder/ndk/include_platform -Iout/soong/.intermediates/hardware/interfaces/power/aidl/android.hardware.power-V4-ndk-source/gen/include -Iexternal/libcxx/include -Iexternal/libcxxabi/include -isystem out/soong/.intermediates/bionic/libc/libc/android_vendor.34_arm64_armv8-a_cortex-a73_shared/gen/include -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi   -Iexternal/libcxxabi/include  -Isystem/core/libutils/include -Isystem/libbase/include -Iexternal/fmtlib/include -Isystem/core/libcutils/include_outside_system -Isystem/logging/liblog/include_vndk -Isystem/core/libprocessgroup/include -Isystem/core/libsystem/include -Ihardware/libhardware/include -Isystem/media/audio/include -Isystem/core/libcutils/include_outside_system -Isystem/core/libsystem/include -Ipackages/modules/Bluetooth/system/types   -isystem out/target/product/spes/obj/include -c  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Wunreachable-code-loop-increment -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fdebug-default-version=5 -fno-strict-aliasing -Werror=date-time -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -Werror=string-plus-int -Werror=unreachable-code-loop-increment -Wno-error=deprecated-declarations -D__compiler_offsetof=__builtin_offsetof -faddrsig -fcommon -Werror=int-conversion -Wno-reserved-id-macro -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-sign-compare -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-gnu-designator -Wno-gnu-folding-constant -Wunguarded-availability -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -ffp-contract=off -fdebug-prefix-map=/proc/self/cwd= -ftrivial-auto-var-init=zero -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang -Wno-unused-command-line-argument -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -fdebug-info-for-profiling -march=armv8-a -mcpu=cortex-a53  -Wsign-promo -Wimplicit-fallthrough -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++17   -fno-rtti -Wall -Wno-unused-parameter -Wno-unused-variable -DDO_NOT_CHECK_MANUAL_BINDER_INTERFACES -D__ANDROID_VNDK__ -D__ANDROID_VENDOR__ -fPIE -DANDROID_STRICT -target aarch64-linux-android34   -Werror=bool-operation -Werror=format-insufficient-args -Werror=implicit-int-float-conversion -Werror=int-in-bool-context -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=xor-used-as-pow -Wno-void-pointer-to-enum-cast -Wno-void-pointer-to-int-cast -Wno-pointer-to-int-cast -Werror=address-of-temporary -Werror=null-dereference -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-pessimizing-move -Wno-non-c-typedef-for-linkage -Wno-align-mismatch -Wno-error=unused-but-set-variable -Wno-error=unused-but-set-parameter -Wno-error=deprecated-builtins -Wno-error=deprecated -Wno-error=single-bit-bitfield-constant-conversion -Wno-error=enum-constexpr-conversion -Wno-reorder-init-list -Wno-implicit-fallthrough -Wno-c99-designator -Wno-implicit-int-float-conversion -Wno-int-in-bool-context -Wno-alloca -Wno-dangling-gsl -Wno-pointer-compare -Wno-final-dtor-non-final-class -Wno-incomplete-setjmp-declaration -Wno-sizeof-array-div -Wno-xor-used-as-pow -Wno-c++17-extensions -flax-vector-conversions=all -Wno-tautological-overlap-compare -Wno-range-loop-analysis -Wno-invalid-partial-specialization -Wno-deprecated-copy -Wno-misleading-indentation -Wno-zero-as-null-pointer-constant -Wno-deprecated-enum-enum-conversion -Wno-deprecated-anon-enum-enum-conversion -Wno-bool-operation -Wno-unused-comparison -Wno-string-compare -Wno-wrong-info -Wno-unsequenced -Wno-unknown-warning-option -Wno-unused-variable -Wno-unused-value -Wno-unused-parameter -Wno-non-c-typedef-for-linkage -Wno-typedef-redefinition -Wno-format -Wno-void-pointer-to-int-cast -Wno-pointer-to-int-cast -Wno-string-concatenation -Wno-void-pointer-to-enum-cast -Wno-incompatible-pointer-types -Wno-format-invalid-specifier-fcommon  -Wno-self-assign -Wno-format -Wno-unused-label -Wno-pointer-sign -Wno-writable-strings -Wno-missing-declarations -Wno-reorder-ctor -Wno-unused-function  -Wno-format-insufficient-args -Wno-sizeof-array-div -Wno-incompatible-function-pointer-types -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -Wno-unqualified-std-cast-call -Wno-bitwise-instead-of-logical -Wno-misleading-indentation -Wno-array-parameter -Wno-gnu-offsetof-extensions  -Wno-format-insufficient-args -Wno-sizeof-array-div -Wno-incompatible-function-pointer-types -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -Wno-unqualified-std-cast-call -Wno-bitwise-instead-of-logical -Wno-misleading-indentation -Wno-array-parameter -Wno-gnu-offsetof-extensions  -MD -MF out/target/product/spes/obj/EXECUTABLES/android.hardware.power-service_intermediates/PowerHintSession.d -o out/target/product/spes/obj/EXECUTABLES/android.hardware.power-service_intermediates/PowerHintSession.o vendor/qcom/opensource/power/PowerHintSession.cpp"
In file included from vendor/qcom/opensource/power/PowerHintSession.cpp:6:
In file included from vendor/qcom/opensource/power/PowerHintSession.h:9:
In file included from out/soong/.intermediates/hardware/interfaces/power/aidl/android.hardware.power-V4-ndk-source/gen/include/aidl/android/hardware/power/WorkDuration.h:8:
frameworks/native/libs/binder/ndk/include_cpp/android/binder_interface_utils.h:95:20: error: allocating an object of abstract class type 'PowerHintSessionImpl'
        T* t = new T(std::forward<Args>(args)...);
                   ^
vendor/qcom/opensource/power/PowerHintSession.cpp:11:108: note: in instantiation of function template specialization 'ndk::SharedRefBase::make<PowerHintSessionImpl>' requested here
    std::shared_ptr<aidl::android::hardware::power::IPowerHintSession> mPowerSession = ndk::SharedRefBase::make<PowerHintSessionImpl>();
                                                                                                           ^
out/soong/.intermediates/hardware/interfaces/power/aidl/android.hardware.power-V4-ndk-source/gen/include/aidl/android/hardware/power/IPowerHintSession.h:51:32: note: unimplemented pure virtual method 'sendHint' in 'PowerHintSessionImpl'
  virtual ::ndk::ScopedAStatus sendHint(::aidl::android::hardware::power::SessionHint in_hint) = 0;
                               ^
out/soong/.intermediates/hardware/interfaces/power/aidl/android.hardware.power-V4-ndk-source/gen/include/aidl/android/hardware/power/IPowerHintSession.h:52:32: note: unimplemented pure virtual method 'setThreads' in 'PowerHintSessionImpl'
  virtual ::ndk::ScopedAStatus setThreads(const std::vector<int32_t>& in_threadIds) = 0;
                               ^
1 error generated.

Change-Id: I9ebd5685f49af72d8efa1bbc5323fb61e492eb71